### ISSUE TITLE
Cambiar el nombre de la clase Test por Questionnarie

### ISSUE THREAD

**Issue by oscarbelmon** [FCT-18-13677/loneliness_tests#1]
El nombre Test puede recordar a las pruebas unitarias. Questionnaire es «cuestionario» en inglés.

**Comment by oscarbelmon** [comment]
Hola @agascocompte. Por fa, cierra este issue si ya está corregido.

**Comment by agascocompte** [comment]
Arreglado, el nombre de la clase Test se ha sustituido por Questionnarie.
