### ISSUE TITLE
Eliminar los bloques de código en los switch - case.

### ISSUE THREAD

**Issue by oscarbelmon** [FCT-18-13677/loneliness_tests#2]
Sustituir los bloques por una llamada a un método. Si nadie más lo va a utilizar, el método que sea privado.

**Comment by oscarbelmon** [comment]
Hola @agascocompte. Por fa, cierra este issue si ya está corregido.

**Comment by agascocompte** [comment]
Arreglado, los bloques de código switch se han sustituido por clases separadas para cada statement.
